name: Push

on:
  push:
    paths:
      - '**.ts'
      - '**.tsx'

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn eslint --fix
      - name: TS Compile
        run: yarn tsc --noEmit
      - name: TS Build 
        run: yarn build
